### ISSUE TITLE
Raise batch size mismatch error.

### ISSUE THREAD

**Issue by familyld** [RuihongQiu/SR-GNN_PyTorch-Geometric#1]
```python
Traceback (most recent call last):
  File "main.py", line 93, in <module>
    main()
  File "main.py", line 73, in main
    forward(model, train_loader, device, writer, epoch, top_k=opt.top_k, optimizer=optimizer, train_flag=True)
  File "/SR-GNN-pg/train.py", line 25, in forward
    scores = model(batch.to(device))
  File "/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/SR-GNN-pg/model.py", line 69, in forward
    hidden = self.gated(embedding, edge_index)
  File "/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/torch_geometric/nn/conv/gated_graph_conv.py", line 64, in forward
    h = self.rnn(m, h)
  File "/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 796, in forward
    self.check_forward_hidden(input, hx)
  File "/anaconda3/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 572, in check_forward_hidden
    input.size(0), hidden_label, hx.size(0)))
RuntimeError: Input batch size 308 doesn't match hidden batch size 309
```

**Comment by RuihongQiu** [comment]
This bug is from the PyG. You need the newest master branch installed. I raised a similar in that repo.

**Comment by familyld** [comment]
> This bug is from the PyG. You need the newest master branch installed. I raised a similar issue in that repo.
Thanks！Update pytorch-geometric to the up-to-date version(1.1.2) can perfectly solve the problem.
